### ISSUE TITLE
Invalid read in unique()

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#15]
`hive::unique` currently looks like this:
```
                for(const_iterator current = cbegin(), end = cend(), previous; current != end;)
                {
                        previous = current++;

                        if (compare(*current, *previous))
                        {
```
Suppose the hive has size 1, we set `current` to `cbegin()`, increment it with `current++` so now it's at `end()`, and then dereference it. This can cause a segfault if things line up just right. For example, this segfaults on my machine:
```
#include "plf_hive.h"
#include <cassert>

int main() {
    plf::hive<int> h = {1, 2, 1, 0, 2, 1, 0, 1, 2, 0};
    h.unique();
}
```
Seems pretty simple to fix; you just have to check `current == end` before dereferencing it.

**Comment by mattreecebentley** [comment]
Thanks, fixed in beta
