### ISSUE TITLE
trim_capacity on an empty hive leaves one group allocated

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#17]
```
#include "plf_hive.h"
#include <cassert>

int main() {
    plf::hive<char> h;
    assert(h.capacity() == 0u);
    h.insert('x');
    h.clear();
    assert(h.size() == 0u);
    assert(h.capacity() > 0u);
    h.trim_capacity();
    assert(h.capacity() == 0u);  // assert-fails
}
```

My understanding, from D0447R20, is that "`.clear()` followed by `.trim_capacity()`" is supposed to be an effective way to return a hive to the default-constructed, capacity-zero state. But it seems that `plf::hive` doesn't actually implement that; instead, `plf::hive`'s `.trim_capacity()` always leaves one extra group allocated.

It's unclear to me whether `plf::hive`'s behavior is:
- unintended,
- intentional but deliberately non-conforming to D0447R20,
- simply a low-QoI implementation of D0447R20, or
- actually a _high_-QoI implementation of D0447R20.

(In my own repo I propose to have `.trim_capacity()` leave no empty groups allocated — its postcondition will be that every allocated group contains at least one element. So, in my implementation, `.trim_capacity()` on an empty hive will always produce the default-constructed capacity-zero state.)

**Comment by Quuxplusone** [comment]
Vice versa, `plf::hive`'s `.assign` can sometimes reduce capacity, which is surprisingly inconsistent with the Big Three vendors' standard containers IMHO. https://eel.is/c++draft/container.requirements#sequence.reqmts-59 implies that `.assign` is totally _permitted_ to reduce capacity; I just think it _shouldn't_ reduce capacity (as a QoI matter).
```
int main()
{
    std::vector<int> v;
    v.reserve(1000);
    v.assign(0, 42);
    printf("%zu\n", v.capacity());  // prints "1000" on all of libc++, libstdc++, MSVC

    std::string s;
    s.reserve(1000);
    s.assign(0, 'x');
    printf("%zu\n", s.capacity());  // prints "1000" or "1007" on all of libc++, libstdc++, MSVC

    plf::hive<int> h;
    h.reserve(1000);
    h.assign(0, 42);
    printf("%zu\n", h.capacity());  // surprisingly prints "0"
}
```

**Comment by mattreecebentley** [comment]
I don't see a reason why it shouldn't on a multi-block container.
For vector and string this is relevant because getting rid of a block 
involves reallocation of elements. It doesn't on deque or hive.

**Comment by mattreecebentley** [comment]
This was a bug related to the way that clear() and insert() interact.
Now fixed in beta.
