### ISSUE TITLE
`reinterpret_cast` to fancy pointers?

### ISSUE THREAD

**Issue by frederick-vs-ja** [mattreecebentley/plf_hive#2]
There's one comment in plf_hive.h saying that "`&*` to avoid problems with non-trivial pointers". I guess the intent is to support fancy pointers ([P0773R0](https://wg21.link/p0773r0)).
However, there are occurences of `reinterpret_cast` whose souce and target types are _`xxx`_`pointer`, which doesn't compile if these types are fancy poiners.

If fancy pointers are intendedly supported by `hive`, I think the following replacement should be used (also works for raw pointers).
```C++
template <class Dst, class PtrSrc>
auto reinterpret_rebind(PtrSrc psrc) -> typename std::poiner_traits<PtrSrc>::template rebind<Dst>
{
        using PtrDst = typename std::poiner_traits<PtrSrc>::template rebind<Dst>;
        return std::pointer_traits<PtrDst>::pointer_to(reintepret_cast<Dst*>(std::to_address(psrc)));
}
```
Note that it's OK to use `std::to_address` because `hive` requires C++20.

**Comment by mattreecebentley** [comment]
The intent was to support allocators which return unique_pointer, shared_pointer etc, not fancy pointers. I do not intend to support allocators returning fancy pointers.
However you're correct in that I am only selectively utilising &*, and this is probably a bug.
Could you advice as to whether &* is sufficient in the context of shared_pointer, unique_pointer etc, if not will take a look at the solution advised, or simply remove the &* for the moment.

**Comment by frederick-vs-ja** [comment]
It's clear that `std::allocator_traits<SomeAllocator>::pointer` should not be a `unique_ptr`/`shared_ptr` (note that they are not random access iterators), otherwise `SomeAllocator` fails to meet the [_Allocator_](https://en.cppreference.com/w/cpp/named_req/Allocator) requirements (a.k.a. [_Cpp17Allocator_](https://eel.is/c++draft/allocator.requirements) in the standard).

I don't think an iterator of a container should store `unique_ptr` (or something representing unique ownership) to the element, because the container certainly owns its elements, and no iterator should take the ownership.

For `shared_ptr`, I think it may be possible for an iterator to share ownership of the allocated storage with the container. However, the direct support for `shared_ptr` is not trivial, at least we should sometimes use `std::reinterpret_pointer_cast` instead of `reinterpret_cast`, and use `sp = std::shared_ptr<T>(std::move(sp), sp.get() + 1)` instead of `++`...

**Comment by mattreecebentley** [comment]
All good - thank you for explaining. In the meantime I implemented a change which supports all pointer types (including fancy pointers potentially), and it doesn't appear to have had any effect on performance (being constexpr), so this is considered fixed now.
