### ISSUE TITLE
reshape() is not exception-safe

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#26]
```
#include "plf_hive.h"
#include <cassert>

int should_throw = 0;
struct S {
    S() = default;
    S(const S&) { if (--should_throw == 0) throw 42; }
};

int main()
{
    plf::hive<S> h;
    h.reshape({10, 10});
    assert(h.block_capacity_hard_limits().min == 3);
    assert(h.block_capacity_hard_limits().max == 255);
    assert(h.block_capacity_limits().min == 10);
    assert(h.block_capacity_limits().max == 10);
    h.insert(S{});
    assert(h.size() == 1);
    assert(h.capacity() == 10);
    try {
        should_throw = 1;
        h.reshape({100, 100});
        assert(false);
    } catch (int) {}
    assert(h.size() == 1);
    assert(h.block_capacity_limits().min == 100);
    assert(h.block_capacity_limits().max == 100);
    assert(h.capacity() == 10);  // !!!
}
```

Whenever `h.block_capacity_limits().min == h.block_capacity_limits().max`, we should have a mathematical invariant that `h.capacity() % h.block_capacity_limits().min == 0` (because all the blocks should be of that one capacity). In fact, `reshape` makes it possible to "half-reshape" a hive such that it thinks its _`current-limits`_ are X, but the block list itself respects some other limits Y.

**Comment by mattreecebentley** [comment]
Thanks, fixed now - exception should roll min/max back to what they were, so above code will still fail on last few asserts. Updated paper accordingly
