### ISSUE TITLE
Hive of Vec4f - static_assert - extented alignment

### ISSUE THREAD

**Issue by soufianekhiat** [mattreecebentley/plf_hive#27]
Not an issue but with Visual Studio 2022 - 14.32.31326 - /cpp lastest:
Related to:
`typedef typename std::aligned_storage<sizeof(element_type), (sizeof(element_type) >= (sizeof(skipfield_type) * 2) || alignof(element_type) >= (sizeof(skipfield_type) * 2)) ? alignof(element_type) : (sizeof(skipfield_type) * 2)>::type aligned_element_type; // align element to be at-least 2*skipfield_type width in order to support free list indexes in erased element memory space`

Produces this static_assert:
`type_traits(987,19): error C2338: static_assert failed: 'You've instantiated std::aligned_storage<Len, Align> with an extended alignment (in other words, Align > alignof(max_align_t)). Before VS 2017 15.8, the member "type" would non-conformingly have an alignment of only alignof(max_align_t). VS 2017 15.8 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility (*only* for uses of aligned_storage with extended alignments). Please define either (1) _ENABLE_EXTENDED_ALIGNED_STORAGE to acknowledge that you understand this message and that you actually want a type with an extended alignment, or (2) _DISABLE_EXTENDED_ALIGNED_STORAGE to silence this message and get the old non-conforming behavior.`

So by default it refuse to compile need to explicit: _ENABLE_EXTENDED_ALIGNED_STORAGE or _DISABLE_EXTENDED_ALIGNED_STORAGE.

**Comment by mattreecebentley** [comment]
Implemented, thanks-
