### ISSUE TITLE
Const-correctness: H::const_iterator should not be convertible to H::iterator

### ISSUE THREAD

**Issue by Quuxplusone** [mattreecebentley/plf_hive#7]
```
#include "plf_hive.h"
#include <type_traits>

using H = plf::hive<int>;
static_assert(!std::is_convertible_v<H::const_iterator, H::iterator>); // fails
static_assert(!std::is_convertible_v<H::const_reverse_iterator, H::reverse_iterator>); // fails
```

FWIW IMHO this isn't a very high-priority bug. I mean, sure, it's not rock-solid STL-level quality, but the exact metaprogramming to get all the right conversions in the right places is pretty fiddly. (See https://quuxplusone.github.io/blog/2018/12/01/const-iterator-antipatterns/ )

This hole in `plf::hive`'s const-correctness allows the user-programmer to do silly things like:
```
#include "plf_hive.h"

int main() {
    const plf::hive<int> h = {1, 2, 3, 4};
    plf::hive<int>::iterator it = h.begin();  // you shouldn't allow this
    *it += 42;  // this line modifies the contents of the const hive
}
```

**Comment by mattreecebentley** [comment]
I agree-
using a templated iterator was an initial suggestion to me, which I 
followed, but it has it's downsides.
The only alternative (as far as I know) is a restructuring based on 
inheritance - which involves a lot more code.

If you have a suggestion for overloading the conversions to prevent 
const->non_const without switching to an inheritance model, please fill 
me in.

**Comment by Quuxplusone** [comment]
https://quuxplusone.github.io/blog/2018/12/01/const-iterator-antipatterns/ describes one (actually, two or three ;)) ways to do it, with their upsides and downsides. If you don't mind spoilers in the form of code, see https://github.com/Quuxplusone/SG14/blob/fd6dfac/include/sg14/plf_hive.h#L272-L307 , which implements the specific pattern described in this paragraph:
https://quuxplusone.github.io/blog/2018/12/01/const-iterator-antipatterns/#personally-i-would-be-inclined-t

Switching to public inheritance would be much worse, because of
https://quuxplusone.github.io/blog/2021/07/14/an-iterator-is-not-a-const-iterator/

**Comment by mattreecebentley** [comment]
Good to know-
fixed in beta.
There's a slightly faster way to do the unconst approach, which I use 
elsewhere in the code too.
